---
title: "{{< var course.number >}}: {{< var course.title >}}"
format: html
---

This is the course website for the {{< var course.semester >}} edition of {{< var course.number >}}, {{< var course.title >}}, taught at [{{< var university.name >}}]({{< var university.url >}}) by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}).

## Course Information

Climate variability and change pose threats to lives and livelihoods.
These climate risks can be managed through the design and operation of infrastructure systems, as well as through disaster response and recovery.
Decisions about how to develop and choose risk management strategies are often based on pure vibes, but occasionally rigorous quantitative analyses that make use of scientific information can inform them (we will focus on these cases).
These analyses involve integrating knowledge from multiple disciplines to balance competing goals (objectives) under uncertainty.

In this course, you will learn climate science, uncertainty quantification, and decision analysis methods to support climate risk management.
You will be assigned readings for every class that cover both methods and applications, and will work collaboratively to implement key concepts through programming problem sets.
Active class participation is required.
Methods covered include scenario analysis, exploratory modeling, cost-benefit analysis, single- and multi-objective policy search, reinforcement learning, deep uncertainty, robust decision making, and equitable decision making.

For additional information, see the [syllabus](syllabus.html).

## Instructor

{{< var instructor.name >}} is an assistant professor of Civil and Environmental Engineering at Rice University.
His research integrates Earth science, data science, and decision science to address challenges in climate risk management, water resources, and energy system resilience.
He also teaches CEVE 543 (Data Science for Climate Hazards).

## Software Tools

- This course will use the [Julia](https://julialang.org) programming language. Julia is a modern, free, open source language designed for scientific computing.
- No prior knowledge of Julia is expected, but some exposure to programming is strongly encouraged.
- Assignments will be distributed using [GitHub Classroom](https://github.com).

## Acknowledgements

The layout for this site was inspired by and draws from Vivek Srikrishnan's [Environmental Systems Analysis](https://github.com/vsrikrish/environmental-systems-analysis/) course at Cornell, [STA 210](https://sta210-s22.github.io/website/) at Duke University, and [Andrew Heiss's](https://www.andrewheiss.com/teaching/) course materials at Georgia State.
It builds heavily from my data science for climate hazard assessment course, [CEVE 543](https://ceve543.github.io/).
