<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>CEVE 421/521 - Spring 2024 - Syllabus</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./lectures.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- MathJax 3 -->
<script>
window.MathJax = {
    tex: {
      tags: 'ams'
    }
  };
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="CEVE 421/521 - Spring 2024 - Syllabus">
<meta property="og:description" content="">
<meta property="og:site-name" content="{{< var course.number >}} - {{< var course.semester >}}">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./syllabus.html">Syllabus</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./_assets/logos/Rice_Logo_280_Blue.svg" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">CEVE 421/521</a> 
        <div class="sidebar-tools-main">
    <a href="./{{var course.github}}" rel="" title="Github Repository" class="quarto-navigation-tool px-1" aria-label="Github Repository"><i class="bi bi-github"></i></a>
    <a href="./{{var course.canvas}}" rel="" title="Canvas" class="quarto-navigation-tool px-1" aria-label="Canvas"><i class="bi bi-journal-check"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./syllabus.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lectures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lectures</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./labs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Labs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Resources</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#course-description" id="toc-course-description" class="nav-link active" data-scroll-target="#course-description">Course Description</a></li>
  <li><a href="#course-information" id="toc-course-information" class="nav-link" data-scroll-target="#course-information">Course Information</a>
  <ul class="collapse">
  <li><a href="#prerequisites-preparation" id="toc-prerequisites-preparation" class="nav-link" data-scroll-target="#prerequisites-preparation">Prerequisites &amp; Preparation</a></li>
  <li><a href="#course-objectives" id="toc-course-objectives" class="nav-link" data-scroll-target="#course-objectives">Course Objectives</a></li>
  <li><a href="#required-materials" id="toc-required-materials" class="nav-link" data-scroll-target="#required-materials">Required Materials</a></li>
  </ul></li>
  <li><a href="#a-community-of-learning" id="toc-a-community-of-learning" class="nav-link" data-scroll-target="#a-community-of-learning">A Community of Learning</a>
  <ul class="collapse">
  <li><a href="#core-expectations" id="toc-core-expectations" class="nav-link" data-scroll-target="#core-expectations">Core Expectations</a></li>
  <li><a href="#diversity-equity-and-inclusion" id="toc-diversity-equity-and-inclusion" class="nav-link" data-scroll-target="#diversity-equity-and-inclusion">Diversity, Equity, and Inclusion</a></li>
  <li><a href="#accommodation-for-students-with-disabilities" id="toc-accommodation-for-students-with-disabilities" class="nav-link" data-scroll-target="#accommodation-for-students-with-disabilities">Accommodation for Students with Disabilities</a></li>
  <li><a href="#accommodation-for-scheduling-conflicts" id="toc-accommodation-for-scheduling-conflicts" class="nav-link" data-scroll-target="#accommodation-for-scheduling-conflicts">Accommodation for Scheduling Conflicts</a></li>
  <li><a href="#mask-policies" id="toc-mask-policies" class="nav-link" data-scroll-target="#mask-policies">Mask Policies</a></li>
  <li><a href="#getting-help" id="toc-getting-help" class="nav-link" data-scroll-target="#getting-help">Getting Help</a></li>
  </ul></li>
  <li><a href="#academic-integrity" id="toc-academic-integrity" class="nav-link" data-scroll-target="#academic-integrity">Academic Integrity</a>
  <ul class="collapse">
  <li><a href="#rice-honor-code" id="toc-rice-honor-code" class="nav-link" data-scroll-target="#rice-honor-code">Rice Honor Code</a></li>
  <li><a href="#sec-llm" id="toc-sec-llm" class="nav-link" data-scroll-target="#sec-llm">AI/ML Resource Policy</a></li>
  <li><a href="#policy-on-web-posting-of-course-materials" id="toc-policy-on-web-posting-of-course-materials" class="nav-link" data-scroll-target="#policy-on-web-posting-of-course-materials">Policy on Web Posting of Course Materials</a></li>
  </ul></li>
  <li><a href="#grading" id="toc-grading" class="nav-link" data-scroll-target="#grading">Grading</a>
  <ul class="collapse">
  <li><a href="#reading-quizzes" id="toc-reading-quizzes" class="nav-link" data-scroll-target="#reading-quizzes">Reading Quizzes</a></li>
  <li><a href="#labs" id="toc-labs" class="nav-link" data-scroll-target="#labs">Labs</a></li>
  <li><a href="#tests" id="toc-tests" class="nav-link" data-scroll-target="#tests">Tests</a></li>
  <li><a href="#project" id="toc-project" class="nav-link" data-scroll-target="#project">Project</a></li>
  <li><a href="#reading-discussion" id="toc-reading-discussion" class="nav-link" data-scroll-target="#reading-discussion">Reading Discussion</a></li>
  <li><a href="#late-work-policy" id="toc-late-work-policy" class="nav-link" data-scroll-target="#late-work-policy">Late Work Policy</a></li>
  </ul></li>
  <li><a href="#preliminary-schedule" id="toc-preliminary-schedule" class="nav-link" data-scroll-target="#preliminary-schedule">Preliminary Schedule</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://www.github.com/ceve-421-521/ceve-421-521.github.io/edit/main/syllabus.qmd" class="toc-action">Edit this page</a></p><p><a href="https://www.github.com/ceve-421-521/ceve-421-521.github.io/issues/new" class="toc-action">Report an issue</a></p></div></div><div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="syllabus.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Syllabus</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="course-description" class="level2">
<h2 class="anchored" data-anchor-id="course-description">Course Description</h2>
<p>Climate variability and change pose threats to lives and livelihoods. These climate risks can be managed through the design and operation of infrastructure systems, as well as through disaster response and recovery. Decisions about how to develop and choose risk management strategies are often based on pure vibes, but occasionally rigorous quantitative analyses that make use of scientific information can inform them (we will focus on these cases). These analyses involve integrating knowledge from multiple disciplines to balance competing goals (objectives) under uncertainty.</p>
<p>In this course, you will learn climate science, uncertainty quantification, and decision analysis methods to support climate risk management. You will be assigned readings for every class that cover both methods and applications, and will work collaboratively to implement key concepts through programming problem sets. Active class participation is required. Methods covered include scenario analysis, exploratory modeling, cost-benefit analysis, single- and multi-objective policy search, reinforcement learning, deep uncertainty, robust decision making, and equitable decision making.</p>
</section>
<section id="course-information" class="level2">
<h2 class="anchored" data-anchor-id="course-information">Course Information</h2>
<div class="columns course-details">
<div class="column" style="width:30%;">
<section id="instructor" class="level3">
<h3 class="anchored" data-anchor-id="instructor">Instructor</h3>
<ul>
<li><i class="fa-solid fa-user" title="Name" aria-label="user"></i> <span class="ms-1"><a href="https://jamesdossgollin.me">James Doss-Gollin</a></span></li>
<li><i class="fa-solid fa-envelope" title="Email" aria-label="envelope"></i> <span class="ms-1"><a href="mailto:jdossgollin@rice.edu">jdossgollin@rice.edu</a></span></li>
<li><i class="fa-solid fa-building" title="Office" aria-label="building"></i> <span class="ms-2">Ryon 215</span></li>
</ul>
</section>
</div><div class="column" style="width:30%;">
<section id="ta" class="level3">
<h3 class="anchored" data-anchor-id="ta">TA</h3>
<p>TBD</p>
</section>
</div><div class="column" style="width:30%;">
<section id="meetings" class="level3">
<h3 class="anchored" data-anchor-id="meetings">Meetings</h3>
<ul>
<li><i class="fa-solid fa-calendar" title="Class Days" aria-label="calendar"></i> MWF</li>
<li><i class="fa-solid fa-clock" title="Class Time" aria-label="clock"></i> 11-11:50am</li>
<li><i class="fa-solid fa-university" title="Class Location" aria-label="university"></i> TBD</li>
</ul>
</section>
</div>
</div>
<section id="prerequisites-preparation" class="level3">
<h3 class="anchored" data-anchor-id="prerequisites-preparation">Prerequisites &amp; Preparation</h3>
<p>The following prerequisites are required:</p>
<ul>
<li>An introductory course in probability and statistics, such as CEVE 313, is strictly required.</li>
</ul>
<p>In addition, the following prerequisites are encouraged.</p>
<ul>
<li>Some exposure to Python, Julia, Matlab, R, or another programming language</li>
<li>Additional coursework in applied statistics</li>
<li>Linear algebra (you should be comfortable with matrix notation and basic operations)</li>
<li>Optimization (you should be comfortable writing down optimization problems)</li>
</ul>
<p>If you are unsure whether your background gives you an adequate preparation for this course, <em>please contact the instructor!</em></p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What If My Skills Are Rusty?
</div>
</div>
<div class="callout-body-container callout-body">
<p>If your programming, mathematics, or statistics skills are a little rusty, don’t worry! We will review concepts and build skills over the course of the semester.</p>
</div>
</div>
</section>
<section id="course-objectives" class="level3">
<h3 class="anchored" data-anchor-id="course-objectives">Course Objectives</h3>
<p>After completing this course, you will be able to:</p>
<ol type="1">
<li>Evaluate and describe the strengths and weaknesses of different approaches to modeling the impact of weather and climate hazards on critical systems.</li>
<li>Apply and critique methods for cost-benefit analysis, optimization, policy search, and stochastic control to climate adaptation problems.</li>
<li>Describe multiple frameworks for decision making under deep uncertainty.</li>
<li>Decision analytical frameworks well suited to a particular problem and justify the choice.</li>
</ol>
</section>
<section id="required-materials" class="level3">
<h3 class="anchored" data-anchor-id="required-materials">Required Materials</h3>
<p>No textbook is required for this course. All materials will be posted as open source on <a href="{{<var course.url >}}">the course website</a> or on <a href="https://canvas.rice.edu/courses/{{<var course.canvas_id >}}">Canvas</a>.</p>
<p>You will regularly be assigned scientific papers to read. Where those are available through the Rice library, you will be expected to access them yourself. You are encouraged, though not required, to use Zotero (Rice students have free storage). See <a href="http://fondrenlearning.blogs.rice.edu/zotero/">Fondren Library’s Resources</a> for resources.</p>
<p>You will need a working laptop for this class. If you do not have access to a working laptop, or if you lose access during the semester, please email the instructor.</p>
</section>
</section>
<section id="a-community-of-learning" class="level2">
<h2 class="anchored" data-anchor-id="a-community-of-learning">A Community of Learning</h2>
<p>Rice’s <a href="https://www.rice.edu/mission-values">core values</a> are responsibility, integrity, community, and excellence. Our goal is to create a learning community aligned with these core values.</p>
<section id="core-expectations" class="level3">
<h3 class="anchored" data-anchor-id="core-expectations">Core Expectations</h3>
<p>Course success involves a dual responsibility on the part of the instructor and the student.</p>
<div class="columns">
<div class="column" style="width:48%;">
<p>As the instructor, my responsibility is to provide you with a structure and opportunity to learn. To this end, I commit to:</p>
<ul>
<li>provide organized and focused lectures, in-class activities, and assignments;</li>
<li>encourage students to regularly evaluate and provide feedback on the course;</li>
<li>manage the classroom atmosphere to promote learning;</li>
<li>schedule sufficient out-of-class contact opportunities, such as office hours;</li>
<li>allow adequate time for assignment completion;</li>
<li>make lecture materials, class policies, activities, and assignments accessible to students.</li>
</ul>
</div><div class="column" style="width:4%;">

</div><div class="column" style="width:48%;">
<p>Students are responsible for their own learning in the course and should commit to:</p>
<ul>
<li>attending all lectures;</li>
<li>doing all required preparatory work before class;</li>
<li>actively participating in online and in-class discussions;</li>
<li>beginning assignments and other work early; and</li>
<li>attending office hours as needed.</li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What If I’m Sick?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Please stay home if you’re feeling sick! This is beneficial for both for your own recovery and the health and safety of your classmates. We will also make any necessary arrangements for you to stay on top of the class material and if whatever is going on will negatively impact your grade, for example by causing you to be unable to submit an assignment on time.</p>
</div>
</div>
</section>
<section id="diversity-equity-and-inclusion" class="level3">
<h3 class="anchored" data-anchor-id="diversity-equity-and-inclusion">Diversity, Equity, and Inclusion</h3>
<p>Rice is committed to building and maintaining an equitable and inclusive campus community. Diversity can refer to multiple ways that we identify ourselves, including but not limited to race, color, national origin, language, sex, disability, age, sexual orientation, gender identity, religion, creed, ancestry, belief, veteran status, or genetic information. Each of these diverse identities, along with many others not mentioned here, shape the perspectives our students, faculty, and staff bring to our campus. We, at Rice, will work to promote diversity, equity and inclusion not only because diversity fuels excellence and innovation, but because we want to pursue justice. We acknowledge our imperfections while we also fully commit to the work, inside and outside of our classrooms, of building and sustaining a campus community that increasingly embraces these core values.</p>
<p>Each of us is responsible for creating a safer, more inclusive environment.</p>
</section>
<section id="accommodation-for-students-with-disabilities" class="level3">
<h3 class="anchored" data-anchor-id="accommodation-for-students-with-disabilities">Accommodation for Students with Disabilities</h3>
<p>If you have a documented disability or other condition that may affect academic performance you should: 1) make sure this documentation is on file with the Disability Resource Center (Allen Center, Room 111 / <a href="mailto:adarice@rice.edu">adarice@rice.edu</a> / x5841) to determine the accommodations you need; and 2) talk with me to discuss your accommodation needs.</p>
</section>
<section id="accommodation-for-scheduling-conflicts" class="level3">
<h3 class="anchored" data-anchor-id="accommodation-for-scheduling-conflicts">Accommodation for Scheduling Conflicts</h3>
<p>If any of our class meetings conflict with your religious events, student athletics, or other non-negotiable scheduling conflict, please let me know ASAP so that we can make arrangements for you.</p>
</section>
<section id="mask-policies" class="level3">
<h3 class="anchored" data-anchor-id="mask-policies">Mask Policies</h3>
<p>Masks are welcome but not required in the classroom. However, if a colleague (student, faculty, or staff) requests that others wear a mask, you are <em>strongly encouraged</em> to make them feel safe. Please do not ask someone making such a request to disclose their underlying medical condition. If for some reason you need your instructor or classmates to wear a mask, please let me know and I will communicate this to the class without disclosing your identity.</p>
<p>These policies may change over the course of the semester as the situation evolves.</p>
</section>
<section id="getting-help" class="level3">
<h3 class="anchored" data-anchor-id="getting-help">Getting Help</h3>
<p>You can ask questions through Canvas Discussions and Office Hours. We will make an effort to respond to all Canvas discussion questions within 24 hours, though this won’t always be possible (travel, weekends, etc.). Please do not use email for questions about course content or labs, since other students may have related questions. You <em>should</em> use email for questions about personal matters, such as scheduling conflicts, accommodations, etc.</p>
</section>
</section>
<section id="academic-integrity" class="level2">
<h2 class="anchored" data-anchor-id="academic-integrity">Academic Integrity</h2>
<p>This class is designed to encourage collaboration, and students are encouraged to discuss their work with other students. Engineering as a profession relies upon the honesty and integrity of its practitioners (see <em>e.g.</em> the <a href="https://www.asce.org/-/media/asce-images-and-files/career-and-growth/ethics/documents/asce-code-ethics.pdf">American Society for Civil Engineers’ Code of Ethics</a>). <strong>All work submitted must represent the students’ own work and understanding</strong>, whether individually or as a group (depending on the particulars of the assignment).</p>
<p>If you are ever unclear about academic integrity, please ask! Additionally, always err on the side of providing more information.)</p>
<section id="rice-honor-code" class="level3">
<h3 class="anchored" data-anchor-id="rice-honor-code">Rice Honor Code</h3>
<p>More specifically, all students will be held to the standards of the Rice Honor Code, a code that you pledged to honor when you matriculated at this institution. If you are unfamiliar with the details of this code and how it is administered, you should consult the Honor System Handbook at <a href="https://honor.rice.edu/honor-system-handbook/">honor.rice.edu/honor-system-handbook/</a>. This handbook outlines the University’s expectations for the integrity of your academic work, the procedures for resolving alleged violations of those expectations, and the rights and responsibilities of students and faculty members throughout the process.</p>
</section>
<section id="sec-llm" class="level3">
<h3 class="anchored" data-anchor-id="sec-llm">AI/ML Resource Policy</h3>
<p>Large language models (LLMs), like GPT, are powerful tools for generating text that can be used for coding and doing data analysis. This is at once empowering (LLMs are powerful and can save you time) and risky (LLMs can make mistakes that are hard to detect).</p>
<p>Our general view is that LLMs are powerful tools that you will encounter and use when you leave this classroom, so it’s important to learn how to use them responsibly and effectively. You are generally permitted to use LLMs in this course, but ultimately, you are responsible for guaranteeing, understanding, and interpreting your results. In particular:</p>
<ul>
<li>One of the best applications of LLMs is to write code. This can help accelerate your workflow, especially when you are learning new syntax. However, LLMs can make bad decisions about how to structure your code, can introduce bugs, and can mislead you about what your code is doing. You are responsible for understanding and debugging your code, and for ensuring that it does what you intend it to do.</li>
<li>LLMs should not be used to generate text that you submit as your own work. If you are assigned a writing assignment, the point is to stimulate your thought process, and you short-cut this if you ask a LLM to generate the response for you. This leads to shallow thinking! However, you <em>may</em> use tools including LLMs (but also Grammarly, spell-check, etc.) to help you edit your writing. This can sometimes be a fine line; it’s always better to ask if you’re not sure, and to disclose your use of these tools in your submission</li>
</ul>
<p>The <a href="resources/learn-more.qmd">resources page</a> has links to helpful ideas about LLMs and how to use them.</p>
</section>
<section id="policy-on-web-posting-of-course-materials" class="level3">
<h3 class="anchored" data-anchor-id="policy-on-web-posting-of-course-materials">Policy on Web Posting of Course Materials</h3>
<p>Uploading course materials to web sites is not an authorized use of the course material. Both the poster and the user are in violation of the university policy, which is actionable.</p>
</section>
</section>
<section id="grading" class="level2">
<h2 class="anchored" data-anchor-id="grading">Grading</h2>
<p>Your final grade will be calculated as follow:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Category</th>
<th style="text-align: left;">Points (421)</th>
<th style="text-align: left;">Points (521)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Reading quizzes</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Labs</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tests</td>
<td style="text-align: left;">40</td>
<td style="text-align: left;">30</td>
</tr>
<tr class="even">
<td style="text-align: left;">Project</td>
<td style="text-align: left;">40</td>
<td style="text-align: left;">40</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Reading Discussion</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">10</td>
</tr>
</tbody>
</table>
<section id="reading-quizzes" class="level3">
<h3 class="anchored" data-anchor-id="reading-quizzes">Reading Quizzes</h3>
<p>The purpose of assigning readings is to enhance class discussions. Students who are prepared for class enhance the learning experience for everyone and enable a collaborative group discussion. At the start of classes for which reading was assigned, expect a very short (5 minute) quiz covering basic concepts from the reading. You should be able to get all points on these readings if you have done the reading, even if you found key concepts challenging or confusing.</p>
<p>Your lowest two reading quizzes will be dropped.</p>
</section>
<section id="labs" class="level3">
<h3 class="anchored" data-anchor-id="labs">Labs</h3>
<p>On Fridays we will use class time for hands-on programming exercises (“labs”) to give you guided practice applying the concepts and methods from class. These labs will be announced on <a href="{{<var course.url >}}">the course website</a> ahead of time so anyone who is able can bring a laptop to class. These labs can be done in groups; if you cannot bring a laptop to class for whatever reason, you will be able to (and are encouraged to) work with other students, though you must turn in your own assignment for grading. All labs will cover either a set of programming tools or a case study.</p>
<p>Your lowest two labs will be dropped.</p>
</section>
<section id="tests" class="level3">
<h3 class="anchored" data-anchor-id="tests">Tests</h3>
<p>In-class written exams will be given for each module of the course. Tests are designed to be straightforward and will cover key ideas from reading, as well as key terms and concepts from lecture and code interpretation related to labs.</p>
</section>
<section id="project" class="level3">
<h3 class="anchored" data-anchor-id="project">Project</h3>
<p>We will build a case study related to house elevation over the course of the semester through weekly labs. Answers will be posted for each lab, so mistakes made in one lab do not pass to the next.</p>
<p>For a final project, you will be asked to incorporate at least two approaches from the course into the case study. For example, you might improve the representation of additional sources of uncertainty, use a more sophisticated optimization algorithm, or change the objectives of the optimization problem.</p>
</section>
<section id="reading-discussion" class="level3">
<h3 class="anchored" data-anchor-id="reading-discussion">Reading Discussion</h3>
<p>All students enrolled in the 521 section (i.e., graduate students) will present one of the papers assigned to the class and lead a discussion. This discussion should take 30-50 minutes. You will be graded on the quality of your presentation, the depth of your understanding of the reading, and your ability to lead a discussion. You should sign up for a time by the second week of class. You should meet with your instructor at least one week before your presentation to discuss the reading and your discussion plan.</p>
<p>Students enrolled in the 421 section may choose to present a paper alone or in a group. If you choose to present a paper, you will be graded on the same scale as the 521 students.</p>
</section>
<section id="late-work-policy" class="level3">
<h3 class="anchored" data-anchor-id="late-work-policy">Late Work Policy</h3>
<ul>
<li>Late projects will be subjected to a 10% penalty per day. Specifically, your grade will be multiplied <span class="math inline">\(0.9^d\)</span> where <span class="math inline">\(d\)</span> is the number of days late.</li>
<li>Late labs will not be accepted, because we will discuss solutions in class.</li>
</ul>
<p>As described above, your lowest two labs and reading quizzes will be dropped. This is intended to accommodate events like minor illnesses, travel to a conference, and other circumstances that may cause you to miss a lab or quiz. If a major circumstance arises (e.g., a death in the family, a serious illness, etc.) that causes you to miss an extended period of time, please contact the instructor to discuss accommodations.</p>
</section>
</section>
<section id="preliminary-schedule" class="level2">
<h2 class="anchored" data-anchor-id="preliminary-schedule">Preliminary Schedule</h2>
<p>The following schedule outlines our planned topics and readings for the semester. All assignments will be posted on Canvas.</p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Not all readings listed here will be assigned in full. Some may be assigned as optional reading and others may be assigned as excerpts.</p>
</div>
</div>
</div>
<table class="table-striped table-hover table">
<caption></caption>
<colgroup>
<col style="width: 8%">
<col style="width: 16%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>Week</th>
<th>Course Dates</th>
<th>Topic</th>
<th>Reading</th>
<th>Lab</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td><strong>Module 1:</strong></td>
<td><strong>Introduction</strong></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>1</td>
<td>1/8, 1/10, 1/12</td>
<td>Introduction to climate risk management</td>
<td><span class="citation" data-cites="frank_newjersey:2022">Frank (<a href="#ref-frank_newjersey:2022" role="doc-biblioref">2022</a>)</span>, <span class="citation" data-cites="loucks_planning:2017">Loucks (<a href="#ref-loucks_planning:2017" role="doc-biblioref">2017</a>)</span> Ch. 1</td>
<td>Software installation</td>
</tr>
<tr class="odd">
<td>2</td>
<td>1/17, 1/19</td>
<td>Science of climate hazard</td>
<td><span class="citation" data-cites="seneviratne_wg1ch11:2021">Seneviratne et al. (<a href="#ref-seneviratne_wg1ch11:2021" role="doc-biblioref">2021</a>)</span>, <span class="citation" data-cites="lall_ncawater:2018">Lall et al. (<a href="#ref-lall_ncawater:2018" role="doc-biblioref">2018</a>)</span></td>
<td>Julia basics</td>
</tr>
<tr class="even">
<td>3</td>
<td>1/22, 1/24, 1/26</td>
<td>Vulnerability, exposure, and impacts</td>
<td><span class="citation" data-cites="wing_vulnerability:2020">Wing et al. (<a href="#ref-wing_vulnerability:2020" role="doc-biblioref">2020</a>)</span>, <span class="citation" data-cites="bonnafous_waterrisk:2017">Bonnafous et al. (<a href="#ref-bonnafous_waterrisk:2017" role="doc-biblioref">2017</a>)</span></td>
<td>DataFrames, Distributions</td>
</tr>
<tr class="odd">
<td>4</td>
<td>1/29, 1/31, 2/2</td>
<td>Systems</td>
<td><span class="citation" data-cites="reed_multisectordynamics:2022">Reed et al. (<a href="#ref-reed_multisectordynamics:2022" role="doc-biblioref">2022</a>)</span>,</td>
<td><em>No lab (test 1)</em></td>
</tr>
<tr class="even">
<td></td>
<td><strong>Module 2:</strong></td>
<td><strong>Decision Analysis</strong></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>5</td>
<td>2/5, 2/7, 2/8</td>
<td>Cost-benefit analysis</td>
<td><span class="citation" data-cites="arrow_discount:2013">Arrow et al. (<a href="#ref-arrow_discount:2013" role="doc-biblioref">2013</a>)</span></td>
<td>House Elevation Case Study</td>
</tr>
<tr class="even">
<td>6</td>
<td>2/12, 2/14, 2/16</td>
<td>Scenario analysis</td>
<td><span class="citation" data-cites="bankes_exploratory:1993">Bankes (<a href="#ref-bankes_exploratory:1993" role="doc-biblioref">1993</a>)</span></td>
<td>BRICK</td>
</tr>
<tr class="odd">
<td>7</td>
<td>2/19, 2/21, 2/23</td>
<td>Policy search and optimization</td>
<td><span class="citation" data-cites="vanberchum_coastal:2019">van Berchum et al. (<a href="#ref-vanberchum_coastal:2019" role="doc-biblioref">2019</a>)</span>, <span class="citation" data-cites="schwetschenau_optimizing:2023">Schwetschenau et al. (<a href="#ref-schwetschenau_optimizing:2023" role="doc-biblioref">2023</a>)</span></td>
<td>Metaheuristics</td>
</tr>
<tr class="even">
<td>8</td>
<td>2/26, 2/28, 3/1</td>
<td>Multiobjective policy search</td>
<td><span class="citation" data-cites="zarekarizi_suboptimal:2020">Zarekarizi et al. (<a href="#ref-zarekarizi_suboptimal:2020" role="doc-biblioref">2020</a>)</span></td>
<td>BlackBoxOptim</td>
</tr>
<tr class="odd">
<td>9</td>
<td>3/4, 3/6, 3/8</td>
<td>Sequential decision problems</td>
<td><span class="citation" data-cites="herman_control:2020">Herman et al. (<a href="#ref-herman_control:2020" role="doc-biblioref">2020</a>)</span>, <span class="citation" data-cites="quinn_dps:2017">Quinn et al. (<a href="#ref-quinn_dps:2017" role="doc-biblioref">2017</a>)</span>, <span class="citation" data-cites="fletcher_mombasa:2019">Fletcher et al. (<a href="#ref-fletcher_mombasa:2019" role="doc-biblioref">2019</a>)</span>, <span class="citation" data-cites="sutton_reinforcement:2018">Sutton &amp; Barto (<a href="#ref-sutton_reinforcement:2018" role="doc-biblioref">2018</a>)</span></td>
<td>Case Study: The Parking Garage</td>
</tr>
<tr class="even">
<td>10</td>
<td>3/18, 3/20, 3/22</td>
<td>Robustness</td>
<td><span class="citation" data-cites="herman_robustness:2015">Herman et al. (<a href="#ref-herman_robustness:2015" role="doc-biblioref">2015</a>)</span>, <span class="citation" data-cites="mcphail_robustness:2019">McPhail et al. (<a href="#ref-mcphail_robustness:2019" role="doc-biblioref">2019</a>)</span></td>
<td>Case Study: The Lake Problem</td>
</tr>
<tr class="odd">
<td></td>
<td><strong>Module 3:</strong></td>
<td><strong>Thinking Critically</strong></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>11</td>
<td>3/25, 3/27, 3/29</td>
<td>Deep uncertainty</td>
<td><span class="citation" data-cites="schneider_scenarios:2002">Schneider (<a href="#ref-schneider_scenarios:2002" role="doc-biblioref">2002</a>)</span>, <span class="citation" data-cites="lempert_robust:2000">Lempert &amp; Schlesinger (<a href="#ref-lempert_robust:2000" role="doc-biblioref">2000</a>)</span>, <span class="citation" data-cites="oreskes_verification:1994">Oreskes et al. (<a href="#ref-oreskes_verification:1994" role="doc-biblioref">1994</a>)</span></td>
<td><em>No lab (test 2)</em></td>
</tr>
<tr class="odd">
<td>12</td>
<td>4/1, 4/3, 4/5</td>
<td>Equity and justice</td>
<td><span class="citation" data-cites="pollack_equity:2023">Pollack et al. (<a href="#ref-pollack_equity:2023" role="doc-biblioref">2023</a>)</span>, <span class="citation" data-cites="fletcher_waterresourcesequity:2022">Fletcher et al. (<a href="#ref-fletcher_waterresourcesequity:2022" role="doc-biblioref">2022</a>)</span></td>
<td><em>No lab</em></td>
</tr>
<tr class="even">
<td>13</td>
<td>4/10, 4/12</td>
<td>Financial and systemic risks</td>
<td><span class="citation" data-cites="thomson_systemic:2023">Thomson et al. (<a href="#ref-thomson_systemic:2023" role="doc-biblioref">2023</a>)</span>, <span class="citation" data-cites="condon_myopia:2021">Condon (<a href="#ref-condon_myopia:2021" role="doc-biblioref">2021</a>)</span></td>
<td><em>No lab</em></td>
</tr>
<tr class="odd">
<td>14</td>
<td>4/15, 4/17, 4/19</td>
<td>Reflections</td>
<td><span class="citation" data-cites="keller_management:2021">Keller et al. (<a href="#ref-keller_management:2021" role="doc-biblioref">2021</a>)</span>, <span class="citation" data-cites="gilligan_beyondwickedness:2020">Gilligan &amp; Vandenbergh (<a href="#ref-gilligan_beyondwickedness:2020" role="doc-biblioref">2020</a>)</span></td>
<td><em>No lab (test 3)</em></td>
</tr>
</tbody>
</table>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-line-spacing="2" role="list">
<div id="ref-arrow_discount:2013" class="csl-entry" role="listitem">
Arrow, K., Cropper, M., Gollier, C., Groom, B., Heal, G., Newell, R., et al. (2013). Determining benefits and costs for future generations. <em>Science</em>, <em>341</em>(6144), 349–350. <a href="https://doi.org/10.1126/science.1235665">https://doi.org/10.1126/science.1235665</a>
</div>
<div id="ref-bankes_exploratory:1993" class="csl-entry" role="listitem">
Bankes, S. (1993). Exploratory modeling for policy analysis. <em>Operations Research</em>, <em>41</em>(3), 435–449. <a href="https://doi.org/c7rgcr">https://doi.org/c7rgcr</a>
</div>
<div id="ref-bonnafous_waterrisk:2017" class="csl-entry" role="listitem">
Bonnafous, L., Lall, U., &amp; Siegel, J. (2017). A water risk index for portfolio exposure to climatic extremes: Conceptualization and an application to the mining industry. <em>Hydrology and Earth System Sciences</em>, <em>21</em>(4), 2075–2106. <a href="https://doi.org/f96k67">https://doi.org/f96k67</a>
</div>
<div id="ref-condon_myopia:2021" class="csl-entry" role="listitem">
Condon, M. (2021). Market myopia’s climate bubble. <a href="https://doi.org/10.2139/ssrn.3782675">https://doi.org/10.2139/ssrn.3782675</a>
</div>
<div id="ref-fletcher_mombasa:2019" class="csl-entry" role="listitem">
Fletcher, S., Lickley, M., &amp; Strzepek, K. (2019). Learning about climate change uncertainty enables flexible water infrastructure planning. <em>Nature Communications</em>, <em>10</em>(1), 1782. <a href="https://doi.org/10.1038/s41467-019-09677-x">https://doi.org/10.1038/s41467-019-09677-x</a>
</div>
<div id="ref-fletcher_waterresourcesequity:2022" class="csl-entry" role="listitem">
Fletcher, S., Hadjimichael, A., Quinn, J., Osman, K., Giuliani, M., Gold, D., et al. (2022). Equity in <span>Water Resources Planning</span>: <span>A Path Forward</span> for <span>Decision Support Modelers</span>. <em>Journal of Water Resources Planning and Management</em>, <em>148</em>(7), 02522005. <a href="https://doi.org/10.1061/(ASCE)WR.1943-5452.0001573">https://doi.org/10.1061/(ASCE)WR.1943-5452.0001573</a>
</div>
<div id="ref-frank_newjersey:2022" class="csl-entry" role="listitem">
Frank, T. (2022, August 22). Bold <span>New Jersey Shore Flood Rules Could Be Blueprint</span> for <span>Entire U</span>.<span>S</span>. <span>Coast</span>. <em>Scientific American</em>. Retrieved from <a href="https://www.scientificamerican.com/article/bold-new-jersey-shore-flood-rules-could-be-blueprint-for-entire-u-s-coast/">https://www.scientificamerican.com/article/bold-new-jersey-shore-flood-rules-could-be-blueprint-for-entire-u-s-coast/</a>
</div>
<div id="ref-gilligan_beyondwickedness:2020" class="csl-entry" role="listitem">
Gilligan, J. M., &amp; Vandenbergh, M. P. (2020). Beyond wickedness: Managing complex systems and climate change. <em>Vanderbilt Law Review</em>, <em>73</em>, 1777–1810. Retrieved from <a href="https://wp0.vanderbilt.edu/lawreview/2020/12/beyond-wickedness-managing-complex-systems-and-climate-change/">https://wp0.vanderbilt.edu/lawreview/2020/12/beyond-wickedness-managing-complex-systems-and-climate-change/</a>
</div>
<div id="ref-herman_robustness:2015" class="csl-entry" role="listitem">
Herman, J. D., Reed, P. M., Zeff, H. B., &amp; Characklis, G. W. (2015). How should robustness be defined for water systems planning under change? <em>Journal of Water Resources Planning and Management</em>, <em>141</em>(10), 04015012. <a href="https://doi.org/10.1061/(asce)wr.1943-5452.0000509">https://doi.org/10.1061/(asce)wr.1943-5452.0000509</a>
</div>
<div id="ref-herman_control:2020" class="csl-entry" role="listitem">
Herman, J. D., Quinn, J. D., Steinschneider, S., Giuliani, M., &amp; Fletcher, S. (2020). Climate adaptation as a control problem: <span>Review</span> and perspectives on dynamic water resources planning under uncertainty. <em>Water Resources Research</em>, e24389. <a href="https://doi.org/10.1029/2019wr025502">https://doi.org/10.1029/2019wr025502</a>
</div>
<div id="ref-keller_management:2021" class="csl-entry" role="listitem">
Keller, K., Helgeson, C., &amp; Srikrishnan, V. (2021). Climate risk management. <em>Annual Review of Earth and Planetary Sciences</em>, <em>49</em>(1), 95–116. <a href="https://doi.org/10.1146/annurev-earth-080320-055847">https://doi.org/10.1146/annurev-earth-080320-055847</a>
</div>
<div id="ref-lall_ncawater:2018" class="csl-entry" role="listitem">
Lall, U., Johnson, T., Colohan, P., Aghakouchak, A., Arumugam, S., Brown, C., et al. (2018). Chapter 3: <span>Water</span>. In D. R. Reidmiller, D. R. Easterling, K. E. Kunkel, K. L. M. Lewis, T. K. Maycock, &amp; B. C. Stewart, <em>Impacts, <span>Risks</span>, and <span>Adaptation</span> in the <span>United States</span>: <span>The Fourth National Climate Assessment</span>, <span>Volume II</span></em>. <span>Washington, D.C.</span>: <span>U.S. Global Change Research Program</span>. <a href="https://doi.org/10.7930/NCA4.2018.CH3">https://doi.org/10.7930/NCA4.2018.CH3</a>
</div>
<div id="ref-lempert_robust:2000" class="csl-entry" role="listitem">
Lempert, R. J., &amp; Schlesinger, M. E. (2000). Robust strategies for abating climate change. <em>Climatic Change</em>, <em>45</em>(3-4), 387–401. <a href="https://doi.org/10.1023/A:1005698407365">https://doi.org/10.1023/A:1005698407365</a>
</div>
<div id="ref-loucks_planning:2017" class="csl-entry" role="listitem">
Loucks, D. P. (2017). <em>Water resource systems planning and management: An introduction to methods, models, and applications</em>. <span>Cham</span>: <span>Imprint: Springer</span>.
</div>
<div id="ref-mcphail_robustness:2019" class="csl-entry" role="listitem">
McPhail, C., Maier, H. R., Kwakkel, J. H., Giuliani, M., Castelletti, A., &amp; Westra, S. (2019). Robustness metrics: How are they calculated, when should they be used and why do they give different results? <em>Earth’s Future</em>, 169–191. <a href="https://doi.org/10.1002/2017ef000649">https://doi.org/10.1002/2017ef000649</a>
</div>
<div id="ref-oreskes_verification:1994" class="csl-entry" role="listitem">
Oreskes, N., Shrader-Frechette, K., &amp; Belitz, K. (1994). Verification, validation, and confirmation of numerical models in the <span>Earth</span> sciences. <em>Science</em>. <a href="https://doi.org/10.1126/science.263.5147.641">https://doi.org/10.1126/science.263.5147.641</a>
</div>
<div id="ref-pollack_equity:2023" class="csl-entry" role="listitem">
Pollack, A., Helgeson, C., Kousky, C., &amp; Keller, K. (2023, September 15). Transparency on underlying values is needed for useful equity measurements. <a href="https://doi.org/10.31219/osf.io/kvyxr">https://doi.org/10.31219/osf.io/kvyxr</a>
</div>
<div id="ref-quinn_dps:2017" class="csl-entry" role="listitem">
Quinn, J. D., Reed, P. M., &amp; Keller, K. (2017). Direct policy search for robust multi-objective management of deeply uncertain socio-ecological tipping points. <em>Environmental Modelling &amp; Software</em>, <em>92</em>, 125–141. <a href="https://doi.org/10.1016/j.envsoft.2017.02.017">https://doi.org/10.1016/j.envsoft.2017.02.017</a>
</div>
<div id="ref-reed_multisectordynamics:2022" class="csl-entry" role="listitem">
Reed, P. M., Hadjimichael, A., Moss, R. H., Brelsford, C., Burleyson, C. D., Cohen, S., et al. (2022). Multisector <span>Dynamics</span>: <span>Advancing</span> the <span>Science</span> of <span>Complex Adaptive Human-Earth Systems</span>. <em>Earth’s Future</em>, <em>10</em>(3), e2021EF002621. <a href="https://doi.org/10.1029/2021EF002621">https://doi.org/10.1029/2021EF002621</a>
</div>
<div id="ref-schneider_scenarios:2002" class="csl-entry" role="listitem">
Schneider, S. H. (2002). Can we estimate the likelihood of climatic changes at 2100? <em>Climatic Change</em>, <em>52</em>(4), 441–451. https://doi.org/<a href="http://dx.doi.org/10.1023/A:1014276210717">http://dx.doi.org/10.1023/A:1014276210717</a>
</div>
<div id="ref-schwetschenau_optimizing:2023" class="csl-entry" role="listitem">
Schwetschenau, S. E., Kovankaya, Y., Elliott, M. A., Allaire, M., White, K. D., &amp; Lall, U. (2023). Optimizing <span>Scale</span> for <span>Decentralized Wastewater Treatment</span>: <span>A Tool</span> to <span>Address Failing Wastewater Infrastructure</span> in the <span>United States</span>. <em>ACS ES&amp;T Engineering</em>, <em>3</em>(1), 1–14. <a href="https://doi.org/10.1021/acsestengg.2c00188">https://doi.org/10.1021/acsestengg.2c00188</a>
</div>
<div id="ref-seneviratne_wg1ch11:2021" class="csl-entry" role="listitem">
Seneviratne, S. I., Zhang, X., Adnan, M., Badi, W., Dereczynski, C., Di Luca, A., et al. (2021). Weather and climate extreme events in a changing climate. In V. Masson-Delmotte, P. Zhai, A. Pirani, S. L. Connors, C. Péan, S. Berger, et al. (Eds.), <em>Climate change 2021: <span>The</span> physical science basis. <span>Contribution</span> of working group <span>I</span> to the sixth assessment report of the intergovernmental panel on climate change</em>. Book section, <span>Cambridge, UK and New York, NY, USA</span>: <span>Cambridge University Press</span>. <a href="https://doi.org/10.1017/9781009157896.013">https://doi.org/10.1017/9781009157896.013</a>
</div>
<div id="ref-sutton_reinforcement:2018" class="csl-entry" role="listitem">
Sutton, R. S., &amp; Barto, A. G. (2018). <em>Reinforcement learning: An <span>Introduction</span></em> (Second Edition). <span>Cambridge, Massachusetts and London, England</span>: <span>MIT Press</span>.
</div>
<div id="ref-thomson_systemic:2023" class="csl-entry" role="listitem">
Thomson, H., Zeff, H. B., Kleiman, R., Sebastian, A., &amp; Characklis, G. W. (2023). Systemic <span>Financial Risk Arising From Residential Flood Losses</span>. <em>Earth’s Future</em>, <em>11</em>(4), e2022EF003206. <a href="https://doi.org/10.1029/2022EF003206">https://doi.org/10.1029/2022EF003206</a>
</div>
<div id="ref-vanberchum_coastal:2019" class="csl-entry" role="listitem">
van Berchum, E. C., Mobley, W., Jonkman, S. N., Timmermans, J. S., Kwakkel, J. H., &amp; Brody, S. D. (2019). Evaluation of flood risk reduction strategies through combinations of interventions. <em>Journal of Flood Risk Management</em>, <em>12</em>(S2), e12506. <a href="https://doi.org/10.1111/jfr3.12506">https://doi.org/10.1111/jfr3.12506</a>
</div>
<div id="ref-wing_vulnerability:2020" class="csl-entry" role="listitem">
Wing, O. E. J., Pinter, N., Bates, P. D., &amp; Kousky, C. (2020). New insights into <span>US</span> flood vulnerability revealed from flood insurance big data. <em>Nature Communications</em>, <em>11</em>(1, 1), 1444. <a href="https://doi.org/10.1038/s41467-020-15264-2">https://doi.org/10.1038/s41467-020-15264-2</a>
</div>
<div id="ref-zarekarizi_suboptimal:2020" class="csl-entry" role="listitem">
Zarekarizi, M., Srikrishnan, V., &amp; Keller, K. (2020). Neglecting uncertainties biases house-elevation decisions to manage riverine flood risks. <em>Nature Communications</em>, <em>11</em>(1, 1), 5361. <a href="https://doi.org/10.1038/s41467-020-19188-9">https://doi.org/10.1038/s41467-020-19188-9</a>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Handle positioning of the toggle
      window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Overview</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./lectures.html" class="pagination-link">
        <span class="nav-page-text">Lectures</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Content <i class="fa-solid fa-copyright" aria-label="copyright"></i> 2024 by <a href="https://jamesdossgollin.me">James Doss-Gollin</a>. All content licensed under a <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> <i class="fa-brands fa-creative-commons-by" aria-label="creative-commons-by"></i> <i class="fa-brands fa-creative-commons-nc" aria-label="creative-commons-nc"></i> <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license (CC BY-NC-SA 4.0)</a></div>   
    <div class="nav-footer-center"><strong>Page still under construction.</strong></div>
    <div class="nav-footer-right">Made with <a href="https://julialang.org">Julia</a> and <a href="https://quarto.org/">Quarto</a><br> <a href="https://www.github.com/ceve543/ceve543.github.io">View the source on <i class="fa-brands fa-github" aria-label="github"></i> GitHub</a></div>
  </div>
</footer>



</body></html>